optimizer:
  type: AdamW
  kwargs:
    lr: 1e-4
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/Hybrid.yaml
    others:
      subset: train
      npoints: 1024
      whole: True
      using_saved_features: True

model:
  NAME: ReCon2
  group_size: 32
  num_group: 64
  mask_ratio: 0.7
  embed_dim: 384
  depth: 12
  drop_path_rate: 0.1
  num_heads: 6
  decoder_depth: 4
  with_color: False
  large_embedding: False
  img_queries: 13
  text_queries: 3
  pretrained_model_name: vit_small_patch14_dinov2.lvd142m

npoints: 1024
total_bs: 256
step_per_update: 1
max_epoch: 300
