optimizer:
  type: AdamW
  kwargs:
    lr: 5e-5
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/Cap3D.yaml
    others:
      subset: train
      npoints: 1024
      using_saved_features: True

model:
  NAME: ReCon2
  group_size: 32
  num_group: 64
  mask_ratio: 0.7
  mask_type: causal
  embed_dim: 768
  depth: 12
  drop_path_rate: 0.1
  num_heads: 12
  decoder_depth: 4
  with_color: True
  img_queries: 8
  text_queries: 1
  pretrained_model_name: vit_base_patch32_clip_224.openai

npoints: 1024
total_bs: 512
step_per_update: 1
max_epoch: 300
